Travelling-People/config/routes.rb
Rails.application.routes.draw do
	
  resources :photos
	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users
	resources :conversations, only: [:index, :show] 
	resources :messages, only: [:new, :create]
	resources :message_abuses, only:[:new, :create, :index]
	
	get 'users/search/:username', to: 'users#search', as: 'user_search'
  get 'photos/:id/like', to: 'photos#like', as: 'photo_like'
  post 'photos/:id/comment', to: 'photos#comment', as: 'photo_comments'
  get 'locality/:name', to: 'locality#show', as: 'locality'

	root :to => 'home#index', as: 'root'

	# Reports stuff
	resources :reports do
		resources :report_comments
	end
	get  'reports/:id/like', 				 to: 'reports#like',           as: 'report_like'
	get  'reports/:id/dislike', 	   to: 'reports#dislike',        as: 'report_dislike'

end

Travelling-People/app/models/conversation.rb
class Conversation < ApplicationRecord

	# sender_id e receiver_id sono entrambi degli user id
	belongs_to :sender, class_name: 'User', foreign_key: "sender_id"
	belongs_to :receiver, class_name: 'User', foreign_key: "receiver_id"

	has_many :messages, dependent: :destroy

	validates :sender, uniqueness: {scope: :receiver}

	# class method che controlla se esiste una conversation tra due utenti
	scope :between, -> (sender_id, receiver_id) do
		where(sender_id: sender_id, receiver_id: receiver_id).or(where(sender_id: receiver_id, receiver_id: sender_id)).limit(1)
	end

	def with(current_user)
		sender == current_user ? receiver : sender
	end

	def participates?(user)
		sender == user || receiver == user
	end

	def unread_message_count(current_user)
	    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
	end
	
end

Travelling-People/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
	before_action :set_conversation, except: [:index]
	before_action :check_participating!, except: [:index]

	def index
		@conversations = Conversation.where("sender_id = ? OR receiver_id = ?", current_user.id, current_user.id)
		if @conversations.empty?
			flash[:info] = 'Ancora nessuna chat'
			redirect_to users_path
		end
    		@users = User.where.not(id: current_user.id)
  	end

	def show
  		@message = Message.new
		@conversation.messages.where("user_id != ? AND read = ?", current_user.id, false).update_all(read: true)
	end

	private
	# l'utente deve essere autorizzato a vedere la conversazione
	def set_conversation
		@conversation = Conversation.find(params[:id])
	end

	def check_participating!
  		redirect_to root_path unless @conversation && @conversation.participates?(current_user)
	end
end

Travelling-People/app/helpers/conversations_helper.rb
module ConversationsHelper
end

Travelling-People/app/views/conversations/_conversation.html.erb
<div>
  Chat con <strong><%= conversation.with(current_user).username %></strong>
  <br>
  <em><%= conversation.messages.last.body.truncate(50) %></em>
  <br>
  <%= link_to 'Vedi conversazione', conversation_path(conversation) %>
	<% if !conversation.unread_message_count(current_user).zero? %>
	  (messaggi non letti: <%= conversation.unread_message_count(current_user) %>)
  <% end %>	
  <hr>
</div>

Travelling-People/app/views/conversations/index.html.erb
<h1>Le mie chat:</h1>

<div>
  <%= render @conversations %>
</div>

<%= link_to 'Indietro', users_path %>

Travelling-People/app/views/conversations/show.html.erb
<h1>Chat con <%= @conversation.with(current_user).username %></h1>

<div>
	<%= render @conversation.messages %>
</div>

<%= form_for @message do |f| %>
	<%= hidden_field_tag 'conversation_id', @conversation.id %>
	<%= f.label :Inserisci_messaggio %>
	<br>
  <%= f.text_area :body, required: true %>
	<br>
  <%= f.submit 'Invia'%>
<% end %>

<%= link_to 'Indietro', conversations_path %>