Travelling-People/config/routes.rb
Rails.application.routes.draw do
	
  resources :photos
	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users
	resources :conversations, only: [:index, :show] 
	resources :messages, only: [:new, :create]
	resources :message_abuses, only:[:new, :create, :index]
	
	get 'users/search/:username', to: 'users#search', as: 'user_search'
  get 'photos/:id/like', to: 'photos#like', as: 'photo_like'
  post 'photos/:id/comment', to: 'photos#comment', as: 'photo_comments'
  get 'locality/:name', to: 'locality#show', as: 'locality'

	root :to => 'home#index', as: 'root'

	# Reports stuff
	resources :reports do
		resources :report_comments
	end
	get  'reports/:id/like', 				 to: 'reports#like',           as: 'report_like'
	get  'reports/:id/dislike', 	   to: 'reports#dislike',        as: 'report_dislike'

end

Travelling-People/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  
  has_many :report_comments, dependent: :destroy
  has_many :report_likes, dependent: :destroy

  validates :title, :presence => true
  validates :content, :presence => true
  validates :locality, :presence => true

  validates :user, :presence => true
  validates_associated :report_comments
  validates_associated :report_likes

  geocoded_by :locality do |obj, result|
    if not result.present?
      #errors.add(:locality, "does not exist")
      obj.locality = nil
    end
  end
  before_validation :geocode
end

Travelling-People/app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :redirect_if_not_signed_in, only: [:new, :like, :dislike, :destroy]

  def index
    @reports = Report.all.order('created_at DESC')
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to report_path(:id => @report.id)
    else
      flash.now[:warning] = 'Locality not valid'
      render 'new'
    end
  end

  def destroy
    @report = Report.find(params[:id])
    Report.destroy(@report.id)
    flash[:success] = 'Report eliminato!'
    redirect_to root_path
  end

  def liked?(id)
    @report = Report.find(id)
    return current_user.report_likes.find_by(report_id: @report.id) != nil
  end
  helper_method :liked?

  def like
    @report = Report.find(params[:id])
    if @report.user.id == current_user.id
	      flash[:info] = 'Non puoi mettere like ai tuoi report'
    elsif liked? @report.id
        flash[:info] = 'Hai giá messo un like a questo report'
    else
        ReportLike.create(report_id: @report.id, user_id: current_user.id)
    end
    redirect_to reports_path
  end

  def dislike
    @report = Report.find(params[:id])
    if @report.user.id == current_user.id
	      flash[:info] = 'Non puoi eliminare un like ai tuoi report'
    elsif not liked? @report.id
        flash[:info] = 'Non hai ancore messo un like a questo report'
    else
        rid = ReportLike.find_by(report_id: @report.id, user_id: current_user.id).id
        ReportLike.destroy(rid)
    end
    redirect_to reports_path
  end

  def report_params
    params.require(:report).permit(:content, :title, :locality)
                         .merge(user_id: current_user.id)
  end

end

Travelling-People/app/helpers/reports_helper.rb
module ReportsHelper
end

Travelling-People/app/views/reports/_report.html.erb
<h3>
  <%= link_to truncate(report.title, :length => 60), report_path(:id => report.id), method: :get %>
</h3>
<div class="report-info">
  <h6>
    Created at: <%= report.created_at %>, 
    <div class="report-locality">
      Locality: <%= link_to @report.locality, locality_path(@report.locality) %>
    </div>
    </div>
    <div class="posted-by">Posted by <%= report.user.username %></div>
  </h6>
  <h6>
    Likes: <%= report.report_likes.count %>
    Comments: <%= report.report_comments.count %>
  </h6>
  <div class="report-buttons">
    <% if current_user.present? %>
      <% if liked?(report.id) %>
        <%= button_to "Dislike", report_dislike_path(:id => report.id), method: :get %>
      <% elsif %>
        <%= button_to "Like", report_like_path(:id => report.id), method: :get %>
      <% end %>
    <% end %>
    <% if report.user.id == current_user.id or current_user.admin == true %>
      <%= button_to 'Elimina report', report, method: :delete, data: { confirm: "Vuoi davvero eliminare questo report?" } %>
    <% end %>
  </div>
</div>

<div class="report-content"> 
  <p><%= report.content %></p>
  <hr>
</div>

Travelling-People/app/views/reports/index.html.haml
%ol= render @reports

= link_to 'Indietro', root_path

Travelling-People/app/views/reports/new.html.erb
<h1>Write a new report</h1>
<%= render 'reports/new/report_form' %>

Travelling-People/app/views/reports/show.html.erb
<h3>
  <%= link_to truncate(@report.title, :length => 60), report_path(:id => @report.id), method: :get %>
</h3>
<div class="report-info">
  <h6>
    Created at: <%= @report.created_at %>, 
    <div class="report-locality">
      Locality: <%= link_to @report.locality, locality_path(@report.locality) %>
                           <!-- '/locality/' + @report.locality %> -->
    </div>
    <div class="posted-by">Posted by <%= @report.user.username %></div>
  </h6>
  <h6>
    Likes: <%= @report.report_likes.count %>
    Comments: <%= @report.report_comments.count %>
  </h6>
  <div class="report-buttons">
    <% if current_user.present? %>
      <% if liked?(@report.id) %>
        <%= button_to "Dislike", report_dislike_path(:id => @report.id), method: :get %>
      <% elsif %>
        <%= button_to "Like", report_like_path(:id => @report.id), method: :get %>
      <% end %>
    <% end %>
    <% if @report.user.id == current_user.id %>
      <%= button_to 'Elimina report', @report, method: :delete, data: { confirm: "Vuoi davvero eliminare questo report?" } %>
    <% end %>
  </div>
</div>

<div class="report-content"> 
  <p><%= @report.content %></p>
  <hr>
</div>

<ol>
  <%= render  @report.report_comments %>
</ol>

<h5>Add a comment:</h5>
<%= form_with(model: [ @report, @report.report_comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>