Travelling-People/config/routes.rb
Rails.application.routes.draw do
	
  resources :photos
	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users
	resources :conversations, only: [:index, :show] 
	resources :messages, only: [:new, :create]
	resources :message_abuses, only:[:new, :create, :index]
	
	get 'users/search/:username', to: 'users#search', as: 'user_search'
  get 'photos/:id/like', to: 'photos#like', as: 'photo_like'
  post 'photos/:id/comment', to: 'photos#comment', as: 'photo_comments'
  get 'locality/:name', to: 'locality#show', as: 'locality'

	root :to => 'home#index', as: 'root'

	# Reports stuff
	resources :reports do
		resources :report_comments
	end
	get  'reports/:id/like', 				 to: 'reports#like',           as: 'report_like'
	get  'reports/:id/dislike', 	   to: 'reports#dislike',        as: 'report_dislike'

end

Travelling-People/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
		can :read, :all			# -> visitors    
    
		if user.present?  	# -> users
      can :crud, :Message
			can :crud, :Conversation
			can :read, :User
			can :create, :MessageAbuse
			can [:create, :read, :like], :Report
			can :delete, :Report, user_id: user.id

      if user.admin?  	# -> admin
        can :manage, :all
      end

    end
	end  


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

Travelling-People/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Travelling-People/app/models/conversation.rb
class Conversation < ApplicationRecord

	# sender_id e receiver_id sono entrambi degli user id
	belongs_to :sender, class_name: 'User', foreign_key: "sender_id"
	belongs_to :receiver, class_name: 'User', foreign_key: "receiver_id"

	has_many :messages, dependent: :destroy

	validates :sender, uniqueness: {scope: :receiver}

	# class method che controlla se esiste una conversation tra due utenti
	scope :between, -> (sender_id, receiver_id) do
		where(sender_id: sender_id, receiver_id: receiver_id).or(where(sender_id: receiver_id, receiver_id: sender_id)).limit(1)
	end

	def with(current_user)
		sender == current_user ? receiver : sender
	end

	def participates?(user)
		sender == user || receiver == user
	end

	def unread_message_count(current_user)
	    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
	end
	
end

Travelling-People/app/models/message.rb
class Message < ApplicationRecord

	belongs_to :conversation
	belongs_to :user

	validates :body, :presence => true
	validates :conversation_id, :presence => true
	validates :user_id, :presence => true

	# formatting timestamp
	def message_time
      		created_at.strftime("%d/%m/%y at %l:%M %p")
    	end

end

Travelling-People/app/models/message_abuse.rb
class MessageAbuse < ApplicationRecord

	belongs_to :admin, class_name: 'User', foreign_key: "admin_id"

	validates :body, :presence => true
	validates :admin_id, :presence => true

	validate :receiver_is_admin

	# formatting timestamp
	def message_time
      		created_at.strftime("%d/%m/%y at %l:%M %p")
    	end

	private
	def receiver_is_admin
		if !User.find_by(id: admin_id).admin?
			errors.add(:message_abuse, "Solo l'admin può ricevere messaggi di segnalazione")
		end
	end

end

Travelling-People/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :photo_likes, dependent: :destroy
  has_many :photo_comments, dependent: :destroy
  mount_uploader :image, ImageUploader
end

Travelling-People/app/models/photo_comment.rb
class PhotoComment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

Travelling-People/app/models/photo_like.rb
class PhotoLike < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

Travelling-People/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  
  has_many :report_comments, dependent: :destroy
  has_many :report_likes, dependent: :destroy

  validates :title, :presence => true
  validates :content, :presence => true
  validates :locality, :presence => true

  validates :user, :presence => true
  validates_associated :report_comments
  validates_associated :report_likes

  geocoded_by :locality do |obj, result|
    if not result.present?
      #errors.add(:locality, "does not exist")
      obj.locality = nil
    end
  end
  before_validation :geocode
end

Travelling-People/app/models/report_comment.rb
class ReportComment < ApplicationRecord
  belongs_to :user
  belongs_to :report

  validates :content, :presence => true
  validates :user, :presence => true
  validates :report, :presence => true
end

Travelling-People/app/models/report_like.rb
class ReportLike < ApplicationRecord
  belongs_to :user
  belongs_to :report

  validates :user, :presence => true
  validates :report, :presence => true
end

Travelling-People/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
				 :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

	mount_uploader :fotoProfilo, FotoProfiloUploader
	
	has_many :conversations_sent, class_name: 'Conversation'
	has_many :conversations_received, class_name: 'Conversation'
	has_many :messages, dependent: :destroy
	has_many :message_abuses
	has_many :reports, dependent: :destroy
	has_many :photo_likes, dependent: :destroy

	validate  :dim_fotoProfilo
	validates :username, :presence => true, :uniqueness => true

	def self.from_omniauth(auth) 
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.username = auth.info.name
			user.email = auth.info.email
			user.fotoProfilo = auth.info.image
			user.password = Devise.friendly_token[0,20]
		end
	end

	def self.new_with_session(params, session) 
		super.tap do |user|
			if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
   	end
	end

	private
  def dim_fotoProfilo
		if fotoProfilo.size > 5.megabytes
			errors.add(:fotoProfilo, "L'immagine deve essere inferiore a 5MB")
    end
  end

  has_many :reports, dependent: :destroy
  has_many :report_comments, dependent: :destroy
  has_many :report_likes, dependent: :destroy
end

Travelling-People/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

Travelling-People/app/helpers/application_helper.rb
module ApplicationHelper
end

Travelling-People/app/helpers/comments_helper.rb
module CommentsHelper
end

Travelling-People/app/helpers/home_helper.rb
module HomeHelper
end

Travelling-People/app/helpers/likes_helper.rb
module LikesHelper
end

Travelling-People/app/helpers/locality_helper.rb
module LocalityHelper
end

Travelling-People/app/helpers/messages_helper.rb
module MessagesHelper
end

Travelling-People/app/helpers/photos_helper.rb
module PhotosHelper
end

Travelling-People/app/helpers/reports_helper.rb
module ReportsHelper
end

Travelling-People/app/helpers/users_helper.rb
module UsersHelper
end

Travelling-People/app/views/home/_footer_home_page.html.haml
:javascript
  function load_locality() {
  var locality = document.getElementById('locality_name').value;
  console.log("Redirecting to locality " + locality);
  location.href = "/locality/"+locality; }

%input#locality_name{:name => "locality", :type => "text", :placeholder => "Inserisci località"}/

%input{:onclick => "load_locality()", :type => "button", :value => "Cerca località"}/

%h3 Report più recenti:
= link_to 'Vedi i report più recenti',  reports_path

%br/
%br/
%hr/

-#%h3 Foto più votate:
-#= link_to 'Vedi le foto più votate', '#'

%h3 Popular pics:
- @id_counts = PhotoLike.all.group("photo_id").count.sort_by{|a,b| -b}
- @id_counts.each do |id_count|
-	id = id_count[0]
-	photo = Photo.find(id)
  = image_tag photo.image.thumb.url
  %br/
  = link_to "View", photo_path(id_count)
  %br

Travelling-People/app/views/home/_user_profile.html.haml
:javascript
  function load_user() {
  var user_name = document.getElementById('user_name').value;
  console.log("Redirecting to user " + user_name);
  location.href = "/users/search/"+user_name; }

%h2 Nome utente: #{current_user.username}

- if !current_user.provider
  %h2 Descrizione: #{current_user.descrizione}

- if current_user.fotoProfilo?
  = image_tag current_user.fotoProfilo.url
- else
  = image_tag current_user.fotoProfilo.default_url

%p/
= button_to 'Pubblica un nuovo report', new_report_path, :method => :get 
= button_to 'Pubblica una nuova foto', new_photo_path, :method => :get

%hr/

%input#user_name{:name => "user_name", :type => "text", :placeholder => "Inserisci utente"}/

%input{:onclick => "load_user()", :type => "button", :value => "Cerca utente"}/

%br/
= link_to 'Invia messaggio a un utente', users_path
%br/
%br/
- if !current_user.admin?
  = link_to "Segnala abuso all'amministratore", new_message_abus_path
- else
  = link_to "Controlla segnalazioni", message_abuses_path

Travelling-People/app/views/home/index.html.haml
%br/
%br/
- if current_user
	= render :partial => 'user_profile'
		
%hr/

= render :partial => 'footer_home_page'