Travelling-People/config/routes.rb
Rails.application.routes.draw do
	
  resources :photos
	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users
	resources :conversations, only: [:index, :show] 
	resources :messages, only: [:new, :create]
	resources :message_abuses, only:[:new, :create, :index]
	
	get 'users/search/:username', to: 'users#search', as: 'user_search'
  get 'photos/:id/like', to: 'photos#like', as: 'photo_like'
  post 'photos/:id/comment', to: 'photos#comment', as: 'photo_comments'
  get 'locality/:name', to: 'locality#show', as: 'locality'

	root :to => 'home#index', as: 'root'

	# Reports stuff
	resources :reports do
		resources :report_comments
	end
	get  'reports/:id/like', 				 to: 'reports#like',           as: 'report_like'
	get  'reports/:id/dislike', 	   to: 'reports#dislike',        as: 'report_dislike'

end

Travelling-People/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
				 :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

	mount_uploader :fotoProfilo, FotoProfiloUploader
	
	has_many :conversations_sent, class_name: 'Conversation'
	has_many :conversations_received, class_name: 'Conversation'
	has_many :messages, dependent: :destroy
	has_many :message_abuses
	has_many :reports, dependent: :destroy
	has_many :photo_likes, dependent: :destroy

	validate  :dim_fotoProfilo
	validates :username, :presence => true, :uniqueness => true

	def self.from_omniauth(auth) 
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.username = auth.info.name
			user.email = auth.info.email
			user.fotoProfilo = auth.info.image
			user.password = Devise.friendly_token[0,20]
		end
	end

	def self.new_with_session(params, session) 
		super.tap do |user|
			if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
   	end
	end

	private
  def dim_fotoProfilo
		if fotoProfilo.size > 5.megabytes
			errors.add(:fotoProfilo, "L'immagine deve essere inferiore a 5MB")
    end
  end

  has_many :reports, dependent: :destroy
  has_many :report_comments, dependent: :destroy
  has_many :report_likes, dependent: :destroy
end

Travelling-People/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def google_oauth2
	    @user = User.from_omniauth(request.env["omniauth.auth"])
		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
		    	set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
		else
			session["devise.google_data"] = request.env["omniauth.auth"].except(:extra)
	    	redirect_to new_user_registration_path, alert: @user.errors.full_messages
	    end
	end

	def failure
	 	redirect_to root_path
	end

end

Travelling-People/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id).order('username')
  end

  def search
    name = params[:username]
    @user = User.find_by(username: name)
    if @user.nil?
      flash[:warning] = 'Utente non trovato'
      redirect_to root_path
    else
      redirect_to user_path(@user.id)
    end
  end

  def show
    #	@user = User.find_by(username: params[:user][:username])
    @user = User.find(params[:id])
    @photos = Photo.where(user_id: params[:id])
    if @user.nil?
      flash[:warning] = 'Utente inesistente!'
      redirect_to root_path
    else
      @reports = @user.reports
    end
  end

  def destroy
    @user = User.find(params[:id])
    User.destroy(@user.id)
    flash[:success] = 'Utente eliminato!'
    redirect_to root_path
  end

end

Travelling-People/app/helpers/users_helper.rb
module UsersHelper
end

Travelling-People/app/views/users/_user.html.erb
<li>
	<% if user.admin? %>
	  <%= user.username %> (admin) | <%= link_to 'Inizia conversazione', new_message_path(receiver_id: user) %> (se invece vuoi solo segnalare qualche problema <%= link_to 'clicca su questo link', new_message_abus_path %>)
  <% else %>
    <%= user.username %> | <%= link_to 'Inizia conversazione', new_message_path(receiver_id: user) %>
  <% end %>
</li>

Travelling-People/app/views/users/index.html.erb
<%= link_to 'Visualizza le tue chat', conversations_path %>

<h1>Utenti: </h1>

<ul><%= render @users %></ul>

<%= link_to 'Indietro', root_path %>

Travelling-People/app/views/users/show.html.haml
- if can? :delete, @user
	= button_to 'Elimina utente', @user, method: :delete, data: { confirm: "Vuoi davvero eliminare questo utente?" }

%h2 Profilo di #{@user.username}
- if @user.descrizione==""
	%h5 Nessuna descrizione
- else
	%h2 Descrizione: #{@user.descrizione}


- if @user.fotoProfilo?
	= image_tag @user.fotoProfilo.url
- else
	= image_tag @user.fotoProfilo.default_url

%hr/

%h1 Report pubblicati da #{@user.username}:
%ol= render @reports

%br/
%hr/
%h1 Foto pubblicate da #{@user.username}:
- @photos.each do |photo|
	= image_tag photo.image.thumb.url
	%br/
	= link_to "View", photo_path(photo.id)
	%br/